export LC_ALL=zh_CN.UTF-8
export XIM=fcitx
export XIM_PROGRAM=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
eval `dbus-launch --sh-syntax --exit-with-session`
exec fcitx &

session=${1:-i3}
case $session in
    i3|i3wm    ) exec i3;;
    xfce|xfce4 ) exec startxfce4;;
    *          ) exec $1;;
esac
