#!/usr/bin/env python3
# -*- coding: utf-8 -*-
n=int(input("请输入一个正整数："))

def move(n,a,b,c):
    if n == 0:return
    move(n-1,a,c,b)
    print (a, ' --> ' ,c)
    move(n-1,b,a,c)

move(n,"A","B","C")
