#!/usr/bin/env python3
# -*- coding: utf-8 -*-

b=[]*7
def yao():
    i=1
    s=49
    while i < 4 :
        a=int(input("请输入一个正整数: "))
        if a >= s :
            continue
        s=(a-1)//4*4+(s-a-1)//4*4
        print(i,":",s)
        i=i+1
    s=int(s/4)
    return s
j=1
while j<7:
    b.append(yao())
    j=j+1
shang=b[4]%2+b[5]%2*2+b[6]%2*4
xia=b[1]%2+b[2]%2*2+b[3]%2*4
print(shang,xia)
