#!/bin/bash
#这个是用来梅花易数和查询卦的，下面两个路径请注意保持正确
gua_dir=~/github/jiegua/guaci
other=~/github/jiegua/other
####卦名 乾 兑 离 震 巽 坎 艮 坤
####本卦 1  2  3  4  5  6  7  8 已知
####二进 7  3  5  1  6  2  4  0 求
####综卦 1  5  3  7  2  6  4  8
####错卦 8  7  6  5  4  3  2  1
####变1  5  6  7  8  1  2  3  4
####变2  3  4  1  2  7  8  5  6
####变3  2  1  4  3  6  5  8  7
####变4  5  6  7  8  1  2  3  4
####变5  3  4  1  2  7  8  5  6
####变6  2  1  4  3  6  5  8  7

if [[ $1 =~ help|date|cx|cm|cuo|zong|bian|ben ]];then
	:	
else
	int1=$RANDOM
	int2=$RANDOM
	shang=$[$[$int1-1]%8+1]
	xia=$[$[$int2-1]%8+1]
	dong=$[$[$int1+$int2-1]%6+1]
fi


if [[ $1 == "help" ]];then
	cat $other/help.txt
	exit
fi

if [[ $1 == "date" ]];then
    echo -e "请输入农月份和日期：\n月份：\c"
    read i
    echo -e "日期：\c"
    read j
    shang=$[$[9+$j+$i]%8+1]
    k=`date +%H`
    k=$[$[$k+1]/2+1]
    if [ $k=13 ];then k=1;fi
    xia=$[$[9+$j+$i+$k]%8+1]
    dong=$[$[9+$i+$j+$k]%6+1]
fi
#按卦序查询，2个参数，如：mm cx
if [[ $1 == "cx" ]];then
    echo -e "您想要查询第几个卦？"
    read intx
    echo -e "第几爻？\c"
    read dong
	shang=$[$intx/10+10]
	xia=$[$intx%10]
	gua_shu=`awk -v var1=$shang -v var2=$xia 'NR==var1 {print $var2}' $other/xiantian`
	shang=$[$gua_shu/10]
	xia=$[$gua_shu%10]
fi

#按卦名查询,如: mm cm 丰
if [[ $1 == "cm" ]];then
    echo -e "请输入卦名：\c"
    read str
    echo -e "第几爻：\c"
    read dong
    shang=0
    str1=' '
    until  [[ $str1 == $str ]]
    do
    	shang=$[$shang+1]
	str1=`grep $str $other/xiantian |cut -f $shang`
    done
    xia=`grep -n $str $other/xiantian |cut -d ':' -f 1`
fi

#数字占，2个参数，如：mm cuo
if [[ $1 =~ cuo|zong|bian|ben ]];then
    echo -e "第1个数：\c"
    read int1
    echo -e "第2个数：\c"
    read int2
	shang=$[$[$int1-1]%8+1]
	xia=$[$[$int2-1]%8+1]
	dong=$[$[$int1+$int2-1]%6+1]
	case $1 in 
		cuo)	#错卦 mm cuo
			a=(9 8 7 6 5 4 3 2 1)
			shang=${a[$shang]}
			xia=${a[$xia]}
		;;
		zong)	#综卦 mm zong 3 22
			a=( 9 1 5 3 7 2 6 4 8 )
			zhong=$shang
			shang=${a[$xia]}
			xia=${a[$zhong]}
		;;
		bian)	#变卦 mm bian 3 33
			case $dong in
				1)	a=(9 4 8 2 6 3 7 1 5);;
				2)	a=(9 6 2 8 4 5 1 7 3);;
				3)	a=(9 7 3 5 1 8 4 6 2);;
				4)	a=(9 4 8 2 6 3 7 1 5);;
				5)	a=(9 6 2 8 4 5 1 7 3);;
				6)	a=(9 7 3 5 1 8 4 6 2);;
			esac
			shang=${a[$shang]}
			xia=${a[$xia]}
		;;
	esac
fi

#上下卦数及变爻数已定
dong=${shang}${xia}$dong
gua_shu=${shang}${xia}"0"
	

#####输出
#echo -e "\n\e[1;32m老实人竭诚为您解卦：\e[0m"
a=(9 7 3 5 1 6 2 4 0)
b=()
c=()
shang=${a[$shang]}
xia=${a[$xia]}
b[1]=$[$xia%2]
b[2]=$[$[$xia%4]/2]
b[3]=$[$xia/4]
b[4]=$[$shang%2]
b[5]=$[$[$shang%4]/2]
b[6]=$[$shang/4]
by=$[$dong%10]
echo -e "\n 本卦      变卦      互卦      综卦      错卦"
function huayao(){
	function yao(){
		case $2 in
			0)	[[ $1 == 1 ]] && echo -e "\e[1;31m——  ——\e[0m    \c" || echo -e "——  ——    \c";;
			1)	[[ $1 == 1 ]] && echo -e "\e[1;31m——————\e[0m    \c" || echo -e "——————    \c";;
		esac
	}
	yao $1 $2
	yao $1 $3
	yao $1 $4
	yao $1 $5
	yao $1 $6
 	echo 
}
for i in 6 5 4 3 2 1
do
	if [ $i == $by ];then
		bby=1
		c[$i]=$[1-$[b[$i]]]
	else
		bby=0
		c[$i]=$[b[$i]]
	fi
	hu=(9 2 3 4 3 4 5) 
	huayao $bby $[b[$i]] $[c[$i]] $[b[$[hu[$i]]]] $[b[7-$i]] $[1-$[b[$i]]]
done

echo
head -4 $gua_dir/$gua_shu
echo
head -3 $gua_dir/$dong
echo
tail -3 $gua_dir/$dong

#less $gua_shu
#less $dong

if [ $? != 0 ] ;then echo -e "\e[1;31mError:出现错误了哦！\e[0m";fi
